data = {
    "Aéroport Tunis-Carthage": {
        "Bizerte": 30,
        "Nabeul": 30,
        "Sousse": 50,
        "Monastir": 60,
        "Mahdia": 65,
        "Kairouan": 50,
        "Sfax": 90,
        "Gabès": 130,
        "Djerba": 160,
        "Tozeur": 140,
        "Gafsa": 110,
        "Kasserine": 100,
        "Sidi Bouzid": 90,
        "Béja": 40,
        "Jendouba": 50,
        "Le Kef": 55,
        "Siliana": 50,
        "Zarzis": 170,
        "Médenine": 150,
        "Tataouine": 180,
        "Douz": 170,
        "Ben Guerdane": 170,
        "Matmata": 150
    },
    "Aéroport Enfidha-Hammamet": {
        "Bizerte": 55,
        "Nabeul": 25,
        "Sousse": 20,
        "Monastir": 25,
        "Mahdia": 35,
        "Kairouan": 135,
        "Sfax": 55,
        "Gabès": 100,
        "Djerba": 130,
        "Tozeur": 110,
        "Gafsa": 85,
        "Kasserine": 60,
        "Sidi Bouzid": 60,
        "Béja": 70,
        "Jendouba": 80,
        "Le Kef": 60,
        "Siliana": 45,
        "Zarzis": 140,
        "Médenine": 200,
        "Tataouine": 150,
        "Douz": 140,
        "Ben Guerdane": 140,
        "Matmata": 120
    },
    "Aéroport Monastir": {
        "Bizerte": 70,
        "Nabeul": 38,
        "Sousse": 16,
        "Monastir": 60,
        "Mahdia": 16,
        "Kairouan": 20,
        "Sfax": 40,
        "Gabès": 84,
        "Djerba": 120,
        "Tozeur": 110,
        "Gafsa": 81,
        "Kasserine": 65,
        "Sidi Bouzid": 55,
        "Béja": 85,
        "Jendouba": 100,
        "Le Kef": 75,
        "Siliana": 55,
        "Zarzis": 125,
        "Médenine": 110,
        "Tataouine": 135,
        "Douz": 125,
        "Ben Guerdane": 130,
        "Matmata": 100
    },
    "Aéroport de Djerba": {
        "Bizerte": 180,
        "Nabeul": 150,
        "Sousse": 120,
        "Monastir": 120,
        "Mahdia": 120,
        "Kairouan": 100,
        "Sfax": 90,
        "Gabès": 40,
        "Tozeur": 100,
        "Gafsa": 80,
        "Kasserine": 110,
        "Sidi Bouzid": 100,
        "Béja": 160,
        "Jendouba": 150,
        "Le Kef": 140,
        "Siliana": 130,
        "Zarzis": 30,
        "Médenine": 30,
        "Tataouine": 50,
        "Douz": 70,
        "Ben Guerdane": 30,
        "Matmata": 40
    }
}