name: Auto Version Increment and Tag

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get latest version
        id: version
        run: |
          # Get the latest tag or default to v0.0.0
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest version: $VERSION"

          # Remove the 'v' prefix for version splitting
          VERSION_NO_V=${VERSION#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NO_V"

          # Check the latest commit message for versioning type
          LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Latest commit message: $LATEST_COMMIT_MESSAGE"

          if [[ "$LATEST_COMMIT_MESSAGE" =~ "#NEW" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "$LATEST_COMMIT_MESSAGE" =~ "#FEAT" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ "$LATEST_COMMIT_MESSAGE" =~ "#FIX" ]]; then
            PATCH=$((PATCH + 1))
          else
            # Default: Increment PATCH version
            PATCH=$((PATCH + 1))
          fi

          # New version
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
