name: Auto Version Increment and Tag

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest version
        id: version
        run: |
          # Check for the latest tag and default to v0.0.0 if no tag is found
          VERSION=$(git tag -l | sort -V | tail -n 1 || echo "v0.0.0")
          echo "Latest version: $VERSION"

          # If no tags exist (first run), create the initial v0.0.0 tag
          if [[ "$VERSION" == "v0.0.0" ]]; then
            echo "No tags found, creating v0.0.0 tag"
            git tag v0.0.0
            git push origin v0.0.0  # Push the initial tag
          fi

          # Remove the 'v' prefix from the version string
          VERSION=${VERSION#v}

          # Split the version string into an array (MAJOR.MINOR.PATCH)
          IFS='.' read -r -a VERSION_ARRAY <<< "$VERSION"
          MAJOR=${VERSION_ARRAY[0]}
          MINOR=${VERSION_ARRAY[1]}
          PATCH=${VERSION_ARRAY[2]}

          # Check commit messages for versioning type (MAJOR, MINOR, PATCH)
          COMMITS=$(git log --oneline ${VERSION}..HEAD)
          while IFS= read -r commit; do
            if [[ "$commit" =~ #NEW ]]; then
              MAJOR=$((MAJOR+1))
              MINOR=0
              PATCH=0
              break
            elif [[ "$commit" =~ #FEAT ]]; then
              MINOR=$((MINOR+1))
              PATCH=0
            elif [[ "$commit" =~ #FIX ]]; then
              PATCH=$((PATCH+1))
            fi
          done <<< "$COMMITS"

          # Increment the PATCH if no versioning type was found
          if [[ $MAJOR -eq ${VERSION_ARRAY[0]} && $MINOR -eq ${VERSION_ARRAY[1]} && $PATCH -eq ${VERSION_ARRAY[2]} ]]; then
            PATCH=$((PATCH+1))
          fi

          # New version
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create and push new version tag
        run: |
          # Create and push the new tag (if it's a new version)
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
